### ISSUE TITLE
Enhance checks for companion pull requests

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/parity-processbot#304]
At the moment the bot only cares about Substrate -> Polkadot with the implementation being hardcoded for those two. Polkadot is, however, not the only dependent and CI will be supporting more integrations in the future: https://github.com/paritytech/substrate/pull/9010.

https://github.com/paritytech/ci_cd/issues/159#issue-939082694 talks about some issues which could be avoided by having more checks for *any* companions; the following checks would be triggered when someone comments `bot merge`:

- [x] The companion PR should be mergeable (available in the Github REST API as `mergeable`) (#313)
- [x] The companion PR is not in an organization (https://github.com/isaacs/github/issues/1681#issuecomment-825453532 for context) (#313)
- [ ] The companion PR does not change workflow files (#302)

**Comment by joao-paulo-parity** [comment]
Since the remaining item (https://github.com/paritytech/parity-processbot/issues/302) already has a task for it, I'll be closing this issue.
